name: Checkov Analysis with JSON Upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov on Terraform
        run: |
          checkov -d . --output json > checkov-report.json

      - name: Commit and Push Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Mover archivo al directorio 'reports'
          mkdir -p reports
          mv checkov-report.json reports/

          # Commit y Push
          git add reports/checkov-report.json
          git commit -m "Update Checkov report"
          git push origin main --force
