name: Checkov Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Listar Archivos para Confirmar
      - name: List Files in Directory
        run: ls -R

      # Paso 3: Validar la Configuración Terraform
      - name: Validate Terraform Configuration
        run: terraform validate || echo "Terraform validation failed"

      # Paso 4: Instalar Checkov
      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      # Paso 5: Ejecutar Checkov
      - name: Run Checkov on Terraform
        run: |
          checkov -d . --output json > checkov-report.json || true

      # Paso 6: Subir el Informe
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-report
          path: checkov-report.json

      # Paso 7: Mostrar Resultados
      - name: Display Checkov Results
        run: |
          echo "Checkov Analysis Complete"
          cat checkov-report.json
